package rules;

import com.radicu.ruleengine.model.Variable;

rule "R007"
    salience 50
when
    $fact : Variable(ncs > 1000, xTableCurrent > 6, yTableCurrent > 6)
then
    $fact.setState("Change Bits");
end

rule "R006"
    salience 50
when
    $fact : Variable(anc < 300, ss < 100)
then
    $fact.setState("Machine idle");
end

rule "R005"
    salience 50
when
    $fact : Variable(anc < 8000, ss < 400, xTableCurrent > 2, yTableCurrent > 2)
then
    $fact.setState("In Cycle");
end

rule "R004"
    salience 1
when
    $fact : Variable(state == "Check High", drillingCondition2 < alarmLimit4200, drillingCondition3 < alarmLimit5100)
then
    $fact.setState("False alarm");
    $fact.setState("Replace bits");
    $fact.setState("Back to Start");
end

rule "R003"
    salience 2
when
    $fact : Variable(state == "Check High", drillingCondition2 > alarmLimit2, drillingCondition3 > alarmLimit2)
then
    $fact.setState("Replace bits");
end

rule "R002"
    salience 3
when
    $fact : Variable(spindleCurrent > 6, alarmLimit3200 > 0.0, xTableCurrent > 1, yTableCurrent > 1, drillingCondition1 > 3, drillingCondition2 > 3, drillingCondition3 > 3)
then
    $fact.setState("Check High");
end

rule "R001"
    salience 0
when
    $fact : Variable(spindleCurrent > 100, alarmLimit3200 > 0.0, xTableCurrent > 6, yTableCurrent > 1, drillingCondition1 > 3)
then
    $fact.setState("Continuous reasoning");
end

