package rules;

import com.radicu.ruleengine.model.Spindle;

rule "BWO High"
when
    $spindle : Spindle(
        bwo_acc>bwo_acc_treshold_high,
        bwo_mean>bwo_mean_treshold_high
    )
then
    float decreaseFeed = $spindle.getFeed() * 0.95f;
    float new_bwo_acc_treshold_high = $spindle.getBwo_acc_treshold_high() * 1.1f;
    float new_bwo_mean_treshold_high = $spindle.getBwo_mean_treshold_high() * 1.1f;
    $spindle.adjustRule_BWO(new_bwo_acc_treshold_high, new_bwo_mean_treshold_high);
    $spindle.setFeed(decreaseFeed);
end

rule "ANC High"
when
    $spindle : Spindle(
        anc_acc>anc_acc_treshold_high,
        anc_mean>anc_mean_treshold_high
    )
then
    float decreasedRPM = $spindle.getRpm() * 0.9f;
    float new_anc_acc_treshold_high = $spindle.getAnc_acc_treshold_high() * 1.1f;
    float new_anc_mean_treshold_high = $spindle.getAnc_mean_treshold_high() * 1.1f;
    $spindle.adjustRule_ANC(new_anc_acc_treshold_high, new_anc_mean_treshold_high);
    $spindle.setRpm(decreasedRPM);
end

rule "Drill Change Signal"
when
    $spindle : Spindle(
        ncs>1000,
        ncs_acc>400
    )
then
    float new_anc_acc_treshold_high = 210.0f;
    float new_anc_mean_treshold_high = 6500.0f;
    float new_bwo_acc_treshold_high = 20.0f;
    float new_bwo_mean_treshold_high = 480.0f;
    $spindle.adjustRule_BWO(new_bwo_acc_treshold_high, new_bwo_mean_treshold_high);
    $spindle.adjustRule_ANC(new_anc_acc_treshold_high, new_anc_mean_treshold_high);
    $spindle.changeBit();

end

rule "Drill Force Change 1"
    salience 100
when
    $spindle : Spindle(
        rpm<=145000,
        anc_acc>300.0f,
        anc_mean>7500.0f
    )
then
    float new_anc_acc_treshold_high = 210.0f;
    float new_anc_mean_treshold_high = 6500.0f;
    float new_bwo_acc_treshold_high = 20.0f;
    float new_bwo_mean_treshold_high = 480.0f;
    String reason = "Abnormal";
    $spindle.adjustRule_BWO(new_bwo_acc_treshold_high, new_bwo_mean_treshold_high);
    $spindle.adjustRule_ANC(new_anc_acc_treshold_high, new_anc_mean_treshold_high);
    $spindle.forceChangeBits(reason);
end

rule "Drill Force Change 2"
    salience 100
when
    $spindle : Spindle(
        feed<=1200,
        bwo_acc>48.0f,
        bwo_mean>800.0f
    )
then
    float new_anc_acc_treshold_high = 210.0f;
    float new_anc_mean_treshold_high = 6500.0f;
    float new_bwo_acc_treshold_high = 20.0f;
    float new_bwo_mean_treshold_high = 480.0f;
    String reason = "Wear";
    $spindle.adjustRule_BWO(new_bwo_acc_treshold_high, new_bwo_mean_treshold_high);
    $spindle.adjustRule_ANC(new_anc_acc_treshold_high, new_anc_mean_treshold_high);
    $spindle.forceChangeBits(reason);
end

